# Generated by Django 5.0.2 on 2024-10-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_1",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "player_2",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("shape_1", models.CharField(blank=True, max_length=1, null=True)),
                ("shape_2", models.CharField(blank=True, max_length=1, null=True)),
                ("turn", models.CharField(max_length=1)),
                ("board", models.CharField(default="         ", max_length=9)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
