# Generated by Django 5.0.2 on 2024-10-22 21:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multiplayer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="room_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
