# Generated by Django 5.0.2 on 2024-10-24 12:22

import multiplayer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multiplayer", "0002_game_room_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="room_code",
            field=models.CharField(
                default=multiplayer.models.Game.generate_code, max_length=8
            ),
        ),
    ]
