# Generated by Django 5.0.2 on 2024-10-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("multiplayer", "0003_game_updated_date_alter_game_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="updated_date",
            new_name="last_updated",
        ),
    ]
