# Generated by Django 5.0.2 on 2024-10-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multiplayer", "0004_rename_updated_date_game_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="player_1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
