# Generated by Django 5.0.2 on 2024-10-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multiplayer", "0005_alter_game_player_1_alter_game_player_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="started",
            field=models.BooleanField(default=False),
        ),
    ]
