# Generated by Django 5.0.2 on 2024-11-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multiplayer", "0006_game_started"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="started",
        ),
        migrations.AddField(
            model_name="game",
            name="state",
            field=models.CharField(default="pending", max_length=10),
        ),
    ]
