# Generated by Django 5.0.2 on 2024-05-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player", models.CharField(max_length=50, unique=True)),
                ("difficulty", models.CharField(max_length=10)),
                ("player_shape", models.CharField(max_length=1)),
                ("computer_shape", models.CharField(max_length=1)),
                ("turn", models.CharField(max_length=1)),
                ("board", models.CharField(default="        ", max_length=9)),
            ],
        ),
    ]
