# Generated by Django 5.0.2 on 2024-05-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
