# Generated by Django 5.0.2 on 2024-05-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_game_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="board",
            field=models.CharField(default="         ", max_length=9),
        ),
    ]
